#remote_theme: #broccolini/swiss
#theme_color: red  # You can change this to one of the available colors
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
# Other configuration options...
title: Politics Understood 
description: A brief description of your site
baseurl: "/german_federal_elections" # this should match your repository name
url: "https://lw1989.github.io" # the base hostname & protocol for your site

github_repo: german_federal_elections
# the GitHub repo name for your project
github_username: lw1989

social_link: twitter
social_username: lutzwall

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/