remote_theme: broccolini/swiss
theme_color: red  # You can change this to one of the available colors

# Other configuration options...
title: Politics Understood 
description: A brief description of your site
baseurl: "german_federal_elections/" # the subpath of your site, e.g. /blog
url: "https://lw1989.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/